name: Release

on:
  push:
    tags:
    - "v*"
    branches:
    - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  releases:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build Binaries
      run: |
        GOOS=linux GOARCH=amd64 BUILDPATH=./bin/tcli-linux-amd64 make
        GOOS=linux GOARCH=arm BUILDPATH=./bin/tcli-linux-arm make
        GOOS=linux GOARCH=arm64 BUILDPATH=./bin/tcli-linux-arm64 make
        GOOS=windows GOARCH=amd64 BUILDPATH=./bin/tcli-windows-amd64.exe make
        GOOS=darwin GOARCH=amd64 BUILDPATH=./bin/tcli-darwin-amd64 make
        GOOS=darwin GOARCH=arm64 BUILDPATH=./bin/tcli-darwin-arm64 make

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        draft: true
        artifacts: "./bin/*"