name: Release

on:
  push:
    tags:
    - "v*"
    branches:
    - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  releases:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build Binaries
      run: |
        GOOS=linux GOARCH=amd64 BUILDPATH=./bin/tcli-linux-amd64 make
        GOOS=linux GOARCH=arm BUILDPATH=./bin/tcli-linux-arm make
        GOOS=linux GOARCH=arm64 BUILDPATH=./bin/tcli-linux-arm64 make
        GOOS=windows GOARCH=amd64 BUILDPATH=./bin/tcli-windows-amd64.exe make
        GOOS=darwin GOARCH=amd64 BUILDPATH=./bin/tcli-darwin-amd64 make
        GOOS=darwin GOARCH=arm64 BUILDPATH=./bin/tcli-darwin-arm64 make

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        draft: true
        artif  packages:
  packages:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@326560df218a7ea9cf6ab49bbc88b8b306bb437e

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6d5347c4025fdf2bb05167a2519cac535a14a408

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@fdf7f43ecf7c1a5c7afe936410233728a8c2d9c2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}acts: "./bin/*"
